
// input model

.decl Reference(from : number, to : number)
.input Reference

.decl GCRoot(val : number)
.input GCRoot

// output

.decl Live(val : number)
.output Live

// traversal

Live(ref) :- GCRoot(ref).

Live(to) :-
  Live(from),
  Reference(from, to).

.decl All(val : number)

All(from),
All(to) :-
  Reference(from, to).

All(val) :-
  GCRoot(val).

.decl Dead(val : number)
.output Dead

Dead(val) :-
  All(val),
  !Live(val).
