resolver: lts-22.43

packages:
  - 'external-stg-syntax'
  - 'external-stg'
  - 'external-stg-interpreter'
#  - 'lambda'
#  - 'external-stg-compiler'

extra-deps:
  - dom-lt-0.2.3
  - github: david-christiansen/final-pretty-printer
    commit: 048e8fa2d8b2b7a6f9e4e209db4f67361321eec8

  - github: zlonast/souffle-haskell
    commit: d6074faaf921a55e12bda65c8dcd40aca001b46b

allow-newer: true