name: GHC-WPC CI
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/master'
    steps:
     - uses: DeterminateSystems/nix-installer-action@main
     - name: Cancel Previous Runs
       uses: styfle/cancel-workflow-action@0.9.1
       with:
         access_token: ${{ github.token }}

     - name: Nix channel update
       run: nix-channel --update

     - name: Cabal install
       run: nix-env -iA cabal-install -f '<nixpkgs>'

     - name: Build external-stg-interpreter
       run: nix-shell -p ghc -p bzip2.dev -p zlib.dev --run 'cabal build external-stg-interpreter'

     - name: Test external-stg-interpreter
       run: nix-shell -p 'haskellPackages.ghcWithPackages (p: with p; [ hspec-discover ])' --run 'cabal test external-stg-interpreter'
